<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="MeCab.DotNet" Version="1.2.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.DirectML" Version="1.24.4" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Gpu" Version="1.25.0" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="Tokenizers.DotNet" Version="1.4.1" />
  </ItemGroup>

</Project>
